feature/length
m1nqm1nq/SimilarityChecker-7599 pull request #1
Opened 2024-07-03 08:06 UTC by m1nqm1nq

length check 부분 기능에 대한 검사

2024-07-03 22:51 UTC, binaryfalse81 requested changes
Texture 를 적용해보면 어때요?

2024-07-03 22:51 UTC, binaryfalse81 commented on Testable/test.cpp
> +    SimilarityChecker sc;
Texture 를 적용해보면 어때요?

2024-07-03 23:32 UTC, m1nqm1nq commented on Testable/test.cpp
> +    SimilarityChecker sc;
좋습니다. 적용해보겠습니다~

2024-07-03 23:41 UTC, charmgreen requested changes

2024-07-03 23:41 UTC, charmgreen commented on Similarity/target.cpp
> +        if (lenA == 0 || lenB == 0) return 0;
두 문자열 중 하나의 길이가 0일 때, 라인 19~27에서도 걸릴 것 같은데 17라인 조건을 빼도 되지 않을까요?

2024-07-03 23:50 UTC, m1nqm1nq commented on Similarity/target.cpp
> +        if (lenA == 0 || lenB == 0) return 0;
해당 구문은 Line22와 Line26에 있는 나눗셈에 대한 Divide by zero 방어 구문으로, 필요한 코드로 보입니다. 코드의 목적이 좀 더 명확히 드러날 수 있도록 해당 라인에 주석을 추가하겠습니다. 감사합니다.

2024-07-03 23:53 UTC, m1nqm1nq commented on Similarity/target.cpp
> +        if (lenA == 0 || lenB == 0) return 0;
위 코멘트대로, latest code에 주석을 추가했습니다.

2024-07-03 23:53 UTC, m1nqm1nq commented on Testable/test.cpp
> +    SimilarityChecker sc;
feedback 반영했습니다. 확인 및 approve 부탁드립니다.

2024-07-03 23:57 UTC, yjyjy131 requested changes
private 을 public 아래 위치로 수정하는 건 어떨까요? 메인 로직에 가독성이 더 좋아질 것 같습니다!

2024-07-04 00:14 UTC, binaryfalse81 approved these changes

2024-07-04 00:14 UTC, binaryfalse81 commented on Testable/test.cpp
> +    SimilarityChecker sc;
반영 감사합니다.

2024-07-04 00:16 UTC, charmgreen approved these changes
변경사항 확인했습니다~

2024-07-04 00:16 UTC, gbyl2024 approved these changes

2024-07-04 00:42 UTC, yjyjy131 approved these changes
수정된 코드 확인했습니다~

2024-07-04 00:42 UTC, merged